export const COLOR_THEME = [
    {
        name: "Blue",
        value: "blue",
        gradient: "from-gray-50 to-blue-50",
        primary: "blue",
        cardBg: "bg-white border border-gray-200",
        text: "text-gray-900",
        textSecondary: "text-gray-600",
        textMuted: "text-gray-500",
        button: "bg-blue-600 text-white hover:bg-blue-700",
        accent: "text-blue-600",
        progressBg: "bg-blue-600",
    },
    {
        name: "Green",
        value: "green",
        gradient: "from-gray-50 to-green-50",
        primary: "green",
        cardBg: "bg-white border border-gray-200",
        text: "text-gray-900",
        textSecondary: "text-gray-600",
        textMuted: "text-gray-500",
        button: "bg-green-600 text-white hover:bg-green-700",
        accent: "text-green-600",
        progressBg: "bg-green-600",
    },
    {
        name: "Purple",
        value: "purple",
        gradient: "from-gray-50 to-purple-50",
        primary: "purple",
        cardBg: "bg-white border border-gray-200",
        text: "text-gray-900",
        textSecondary: "text-gray-600",
        textMuted: "text-gray-500",
        button: "bg-purple-600 text-white hover:bg-purple-700",
        accent: "text-purple-600",
        progressBg: "bg-purple-600",
    },
];

export const DAY_OF_WEEK = [
    "Thứ Hai",
    "Thứ Ba",
    "Thứ Tư",
    "Thứ Năm",
    "Thứ Sáu",
    "Thứ Bảy",
    "Chủ Nhật",
];