export const COLOR_THEME = [
  {
    name: "Blue",
    value: "blue",
    gradient: "from-gray-50 to-blue-50",
    primary: "blue",
    cardBg: "bg-white border border-gray-200",
    text: "text-gray-900",
    textSecondary: "text-gray-600",
    textMuted: "text-gray-500",
    button: "bg-blue-600 text-white hover:bg-blue-700",
    accent: "text-blue-600",
    progressBg: "bg-blue-600",
  },
  {
    name: "Green",
    value: "green",
    gradient: "from-gray-50 to-green-50",
    primary: "green",
    cardBg: "bg-white border border-gray-200",
    text: "text-gray-900",
    textSecondary: "text-gray-600",
    textMuted: "text-gray-500",
    button: "bg-green-600 text-white hover:bg-green-700",
    accent: "text-green-600",
    progressBg: "bg-green-600",
  },
  {
    name: "Purple",
    value: "purple",
    gradient: "from-gray-50 to-purple-50",
    primary: "purple",
    cardBg: "bg-white border border-gray-200",
    text: "text-gray-900",
    textSecondary: "text-gray-600",
    textMuted: "text-gray-500",
    button: "bg-purple-600 text-white hover:bg-purple-700",
    accent: "text-purple-600",
    progressBg: "bg-purple-600",
  },
];

export const DAY_OF_WEEK = [
  "Thứ Hai",
  "Thứ Ba",
  "Thứ Tư",
  "Thứ Năm",
  "Thứ Sáu",
  "Thứ Bảy",
  "Chủ Nhật",
];

// Diary constants
export const MOOD_LIST = [
  { value: 0, label: "Bình thường", icon: "Meh", color: "text-gray-400" },
  { value: 1, label: "Vui vẻ", icon: "Smile", color: "text-yellow-400" },
  { value: 2, label: "Buồn", icon: "Frown", color: "text-blue-400" },
  { value: 3, label: "Cáu", icon: "Angry", color: "text-red-500" },
  { value: 4, label: "Hào hứng", icon: "Zap", color: "text-green-500" },
  { value: 5, label: "Mệt", icon: "Coffee", color: "text-amber-700" },
  { value: 6, label: "Khác", icon: "MoreVertical", color: "text-gray-500" },
];

export const EMOJI_SUGGESTIONS = [
  "😊",
  "😄",
  "😍",
  "🥰",
  "😎",
  "🤗",
  "😌",
  "✨",
  "😢",
  "😭",
  "😔",
  "😞",
  "💔",
  "😪",
  "😰",
  "😟",
  "😡",
  "😤",
  "🤬",
  "😠",
  "💢",
  "🔥",
  "👿",
  "😾",
  "🤗",
  "😴",
  "😌",
  "🧘‍♀️",
  "☕",
  "🌙",
  "💤",
  "🛌",
  "🎉",
  "🚀",
  "⚡",
  "🌟",
  "💪",
  "🔥",
  "✨",
  "🎊",
  "❤️",
  "💕",
  "💖",
  "🌈",
  "🌻",
  "🦋",
  "🌸",
  "🍀",
];

// Swipe sensitivity constants
export const SWIPE_CONFIG = {
  THRESHOLD: 50, // Minimum distance for swipe
  ANIMATION_DURATION: 300, // Animation duration in ms
  MAX_DOTS: 10, // Maximum dots in progress indicator
};
